/*

    problem-> max_AND_pair(good).cpp

    Given an array arr[] of N positive elements. The task is to find the Maximum AND Value generated by any pair of element from the array.
Note: AND is bitwise '&' operator.

Input:
The first line of the input contains a single integer T, denoting the number of test cases. Then T test cases follow. Each test-case has two lines of the input, the first line contains an integer denoting the size of an array N and the second line of input contains N positive integers

Output:
For each testcase, print Maximum AND Value of a pair in a separate line.

Constraints:
1 <=T <= 100
1 <= N <= 5*105
1 <= arr[i] <= 5*105

Example:
Input:
2
4
4 8 12 16
4
4 8 16 2

Output:
8
0

Explanation:
Testcase 1: Pair (8,12) has the Maximum AND Value  i.e. 8.
Testcase 2: Maximum AND Value is 0


        */




#include <bits/stdc++.h>
using namespace std;

int main() {
	 int t;
	 cin>>t;
	 while(t--)
	 {
	     int n;
	     cin>>n;
	     int a[n];

	     for(int i=0;i<n;i++)
	     {

	         cin>>a[i];

	     }

	    int ans=0;
	    for(int i=31;i>=0;i--)
	    {
	        int r=ans|(1<<i);
	        int cnt=0;
	        for(int j=0;j<n;j++)
	        {
	            if((a[j]&r)==r)
	            cnt++;
	        }


	        if(cnt>=2)
	        {
	            ans=ans|r;
	        }


	    }

	   cout<<ans<<"\n";



	 }
}
